bases: [
  "configs/base.yaml",
]

binarizer:
  data_dir: "data/notes"

model:
  mode: d3pm
  use_languages: true
  num_languages: 127
  embedding_dim: 256
  region_cycle_len: 3
  use_glu: true
  encoder:
    cls: "modules.backbones.EBF.EBFBackbone"
    kwargs:
      dim: 256
      num_layers: 4
      num_heads: 8
      head_dim: 64
      c_kernel_size: 31
      m_kernel_size: 31
      ffn_type: 'glu' # 'glu', 'ffn', 'cgmlp'
      ffn_latent_drop: 0.0
      ffn_out_drop: 0.1
      use_ls: true
      dropout_attn: 0.0
      out_drop: 0.1
      c_out_drop: 0.1
      c_latent_drop: 0.0
      skip_fist_ffn: true
      skip_out_ffn: true
  segmenter:
    cls: "modules.backbones.EBF.EBFBackbone"
    kwargs:
      dim: 256
      num_layers: 8
      latent_layer_idx: 6
      latent_out_dim: 16
      num_heads: 8
      head_dim: 64
      c_kernel_size: 31
      m_kernel_size: 31
      ffn_type: 'glu' # 'glu', 'ffn', 'cgmlp'
      ffn_latent_drop: 0.0
      ffn_out_drop: 0.1
      use_ls: true
      dropout_attn: 0.0
      out_drop: 0.1
      c_out_drop: 0.1
      c_latent_drop: 0.0
      skip_fist_ffn: true
      skip_out_ffn: true
  estimator:
    cls: "modules.backbones.ebf_with_joint_attention.JEBFBackbone"
    kwargs:
      dim: 256
      num_layers: 4
      num_heads: 8
      head_dim: 64
      pool_token_source: 'learnable'
      c_kernel_size_pool: 7
      m_kernel_size_pool: 5
      c_kernel_size_x: 31
      m_kernel_size_x: 31
      qk_norm: true
      ffn_type: 'glu' # 'glu', 'ffn', 'cgmlp'
      ffn_latent_drop: 0.1
      ffn_out_drop: 0.1
      attn_type: 'joint'  # 'joint', 'split'
      rope_mode: 'mixed'  # 'local', 'global', 'mixed'
      use_region_bias: false
      region_token_num: 1
      pool_merge_mode: 'mean'  # 'mean', 'max', 'first', 'learned', 'attention'
      skip_fist_ffn: true
      skip_out_ffn: true

training:
  augmentation:
    pitch_shifting:
      enabled: true
      prob: 0.5
      min_semitones: -12
      max_semitones: 12
    loudness_scaling:
      enabled: true
      prob: 0.5
      min_db: -6
      max_db: 6
    spectrogram_masking:
      enabled: true
      time_mask_prob: 0.15
      time_mask_max_width: 50
      freq_mask_prob: 0.15
      freq_mask_max_width: 20
      intersect_prob: 0.5
    colored_noise:
      enabled: true
      prob: 0.25
      min_exponent: 0
      max_exponent: 2
    natural_noise:
      enabled: true
      prob: 0.25
      max_repeats: 3
      noise_path_glob: "data/noise/**/*.wav"
    rir_reverb:
      enabled: true
      prob: 0.25
      kernel_path_glob: "data/reverb/**/*.wav"
  loss:
    region_loss:
      neighborhood_size: 5
      exponential_decay: true
    boundary_loss:
      std: 1.0
    note_loss:
      midi_min: 0
      midi_max: 128
      midi_num_bins: 257
      midi_std: 0.5
  validation:
    d3pm_sample_steps: 8
    boundary_decoding_threshold: 0.2
    boundary_decoding_radius: 2
    boundary_matching_tolerance: 5
    note_presence_threshold: 0.2
    pitch_accuracy_tolerance: 0.5
    pitch_overlap_width: 0.5
