from .boundary_loss import GaussianSoftBoundaryLoss, EarthMoversDistanceLoss, ApproachingMomentumLoss
from .note_loss import GaussianBlurredBinsLoss, CascadedDialCaliperLoss
from .region_loss import RegionalCosineSimilarityLoss
